apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: hjunior29/producer:latest
        env:
        - name: CONSUMER_URL
          value: "http://consumer-service:3001/process"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
spec:
  selector:
    app: producer
  ports:
  - port: 3000
    targetPort: 3000