services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - census-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    networks:
      - census-network

  minio:
    image: minio/minio:latest
    hostname: minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - census-network

  jaeger:
    image: jaegertracing/all-in-one:1.51
    hostname: jaeger
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      COLLECTOR_OTLP_ENABLED: true
    networks:
      - census-network

  grafana:
    image: grafana/grafana:10.2.0
    hostname: grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    user: "0"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - census-network

  load-app:
    build: ./load-app
    hostname: load-app
    container_name: load-app
    depends_on:
      - kafka
      - jaeger
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: census-data
      CSV_DATA_PATH: /app/data
      BATCH_SIZE: 1000
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      SERVICE_NAME: load-app
    volumes:
      - ./data:/app/data:ro
    networks:
      - census-network

  store-app:
    build: ./store-app
    hostname: store-app
    container_name: store-app
    depends_on:
      - kafka
      - minio
      - jaeger
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: census-data
      KAFKA_GROUP_ID: store-app-group
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET: census-data
      S3_USE_SSL: false
      BATCH_SIZE: 1000
      FLUSH_INTERVAL: 30
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      SERVICE_NAME: store-app
    networks:
      - census-network

volumes:
  minio-data:
  grafana-data:

networks:
  census-network:
    driver: bridge