apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-app
  namespace: census-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-app
  template:
    metadata:
      labels:
        app: load-app
    spec:
      containers:
      - name: load-app
        image: load-app:latest
        imagePullPolicy: Never  # For minikube with local images
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: SERVICE_NAME
          value: "load-app"
        - name: CSV_DATA_PATH
          value: "/app/data"
        volumeMounts:
        - name: csv-data
          mountPath: /app/data
          readOnly: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: csv-data
        hostPath:
          path: /tmp/census-data  # Mount from minikube host
          type: DirectoryOrCreate
      restartPolicy: Always